### ISSUE TITLE
boost wave exception

### ISSUE THREAD

**Issue by stakewinner00** [foonathan/standardese#32] opened 2016-07-20 20:54 UTC
When runing standardese on my project I found that when using the preprocessor inside a struct inside a class it throws an exception. 

Commenting the preprocessor conditionals or one of the class it doesn't throw.  

```cpp
class Foo {
  struct Bar {
    #ifdef A
    #elif B
    #else
    #warning C
    #endif
  }mybar;
};
```

> $ standardese test.h

> [info] Generating documentation for "test.h"...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::wave::preprocess_exception> >'
  what():  boost::wave::preprocess_exception
zsh: abort      standardese test.h

**Comment by foonathan** [comment] 2016-07-20 20:59
Thanks. I'll take a look as soon as I'm done with the current feature, maybe tomorrow.

**Comment by foonathan** [comment] 2016-07-31 15:57
The problem is your `#warning`, this is actually not a C++ preprocessing directive. Although supported by most compilers, it isn't portable and not supported by Boost.Wave.
That's why it throws this weird exception.

But I'll support it by simply ignoring this kind of error.

**Comment by foonathan** [comment] 2016-08-04 18:32
Should be fixed now (+ better handling of variables declared after a type definition like your mybar).

**Closed** 2016-08-10 09:37 UTC
Labels: bug
