### ISSUE TITLE
Markdown generated is now misparsed by some renderers

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#98] opened 2018-01-15 09:18 UTC
Github renderer is fine: https://github.com/ned14/outcome/blob/master/doc/src/content/reference/result.md

But other renderers are not:
https://ned14.github.io/outcome/reference/result/

I've tested it with a few other online renderers found with Google. They tend to agree with Hugo's renderer.

**Comment by foonathan** [comment] 2018-01-15 09:24
Could you give me a link to an online renderer that doesn't handle it, so I can try and reproduce it?

**Comment by ned14** [comment] 2018-01-15 09:39
http://markdownlivepreview.com/

**Comment by foonathan** [comment] 2018-01-15 09:48
That renderer doesn't seem to allow any HTML.

I've just installed hugo (version 0.32.4-1, using Arch Linux) and following the tutorial here (https://gohugo.io/getting-started/quick-start/) created a simple site (where the contents of my post is the Github result you've linked). I couldn't reproduce any issues.

**Comment by foonathan** [comment] 2018-01-15 09:50
I've now used the docdock theme you're using, still no issues (besides some weird positioning of links which seem just to be some CSS problems).

**Comment by ned14** [comment] 2018-01-15 10:01
Mmm, I'm on a much older Hugo. Will upgrade and see if it's a Hugo bug. Thanks Jonathan.

**Comment by ned14** [comment] 2018-01-15 14:18
I just upgraded to Hugo 0.32.4, same problem.

Try https://stackedit.io/app. It shows the exact same formatting problem. The cause is the indent of the \<span>, if you remove the indent it renders correctly.

**Comment by ned14** [comment] 2018-01-15 18:47
Both the markdown and mmark renderers produce the same problem.

**Comment by foonathan** [comment] 2018-01-15 20:29
I now see why it worked for me: the file you've linked doesn't contain the change yet that caused the issue.

**Comment by foonathan** [comment] 2018-01-15 20:36
Could you try the fix I've committed to the `markdown-output-fix` branch?

**Comment by ned14** [comment] 2018-01-15 21:30
I'm really sorry to have wasted your time again Jonathan. I'll admit to being both frazzled and tired. It's affecting me.

I pushed the output from the `markdown-output-fix` branch just there. No improvement.

I think you need to stop indenting the `<span>`'s. I appreciate it won't be as pretty, but I can also see how a Markdown parser would get confused by an indented line following a line break. That means something to markdown.

**Comment by foonathan** [comment] 2018-01-16 09:11
I've copied the contents of https://raw.githubusercontent.com/ned14/outcome/master/doc/src/content/reference/result.md into the stackedit app, works fine.

You're saying indent, maybe it's a tabs vs spaces issue?

**Comment by foonathan** [comment] 2018-01-16 09:21
Okay, running hugo locally on the contents of doc/src reproduces the issue.

**Comment by foonathan** [comment] 2018-01-16 09:29
Okay, I've reverted the previous change that caused the issue and added a `style="display: none"` to prevent the whitespace from showing up. Should all be fixed now.

**Comment by foonathan** [comment] 2018-01-16 09:30
As a heads up: I'm off to university, maybe I'll get something done on the train, maybe not. Will push the final changes to standardese in roughly 12 hours at the latest, does that work with the code freeze?

**Comment by ned14** [comment] 2018-01-16 09:48
Cool, mangled HTML is now fixed, thanks.

For me personally the only remaining big issue is the lack of macro parameter docs, so issue #86 because I know full well the reviewers will complain about it, and I'll have to keep repeating myself ad nauseum that it's logged already. But in the end, I can live with that.

I'll take a proper review of the docs when I get into work, I spend most of my day there staring at the wall anyway. And thanks for all your help and work Jonathan. You've been a star.

**Comment by foonathan** [comment] 2018-01-16 10:01
Yes, my plans are implementing that and adding the full scope names to the headings of entities to make it more clear which is a member of what.

**Comment by ned14** [comment] 2018-01-17 19:10
FYI I ran into this problem again after adding headings.

I've implemented a hack you might want to consider yourself: in the \<pre> sections top of each page, don't indent with space, indent with \&nbsp;. That stops the markdown parser getting confused.

**Comment by foonathan** [comment] 2018-01-18 06:45
What kind of headings did you add an how exactly?

**Comment by ned14** [comment] 2018-01-18 21:34
You'll see immediately at https://raw.githubusercontent.com/ned14/outcome/master/doc/src/content/reference/result.md. God it looks ugly. But it works.

**Comment by foonathan** [comment] 2018-02-01 08:10
For me it works even without the non-breaking space.

**Closed** 2018-06-06 11:41 UTC
Labels: bug, cant-reproduce, output
