### ISSUE TITLE
Lists on tparam not rendering correctly

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#60] opened 2017-06-21 01:57 UTC
```
  /*! Provides the result of a success, a success with additional information, or a failure.
  \group result
  \tparam R The type of the successful result.
  \tparam EC The type of the failure/info result.
  \requires Must be DefaultConstructible and BooleanTestable e.g. `if(ec)`
  \tparam NoValuePolicy Policy on how to interpret type `EC` when a wide observation of a not present value occurs.
  Default is:
  - If C++ exceptions are enabled:
      - If `EC` convertible to a `std::error_code`, `throw std::system_error(error())`.
      - If `EC` convertible to a `std::exception_ptr`, `std::rethrow_exception(error())`.
      - If `EC` is `void`, call `std::terminate()`.
      - Else `throw error()`.
  - If C++ exceptions are not enabled, call `std::terminate()`.
  */
  template <class R, class EC = error_code_extended, class NoValuePolicy = policy::default_result_policy<EC>> class result : public result_base<result<R, EC, NoValuePolicy>, R, EC, NoValuePolicy>
```

What I would expect is that an indented bullet list appears on the tparam NoValuePolicy. It does not.

Also, there is no Requires section on the tparam EC.

**Comment by foonathan** [comment] 2017-06-21 07:13
I've already redone the comment parsing, should be fixed there. Will be pushed soon™, once I find the time to integrate it.

Regarding the requires section, this is currently by design - a param cannot contain sections. You can either put it in the parent entity and say `\requires Parameter EC must be …`, or use `\entity result.EC` in an outside comment.

**Comment by ned14** [comment] 2017-06-21 12:26
Cool, looking forward to it

**Comment by foonathan** [comment] 2017-11-28 17:05
That bug is fixed and lists on inline comments are supported as well.

**Closed** 2017-11-28 17:55 UTC
